parser: babel-eslint
env:
  commonjs: true
  jquery: true
  browser: true
  node: true
  es6: true
rules:
  indent:
    - 2
    - 2
  no-console: 1
  no-undef: 2
  semi: 1
  no-unused-vars:
    - 1
    -
      vars: all
      args: after-used
